sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t stephengrider/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stephengrider/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: $BUCKET_NAME
  bucket_path: 'docker-react'
  on:
    branch: main
  access_key_id : $AWS_ACCESS_KEY
  secret_acess_key: $AWS_SECRET_KEY